begin;

-- Product cards may optionally send shoppers to an administrator-controlled URL.
-- Slugs remain internal routing identifiers and are generated by the server.
alter table public.catalog_products
  add column if not exists product_url text;

alter table public.catalog_products
  drop constraint if exists catalog_products_product_url_check;
alter table public.catalog_products
  add constraint catalog_products_product_url_check check (
    product_url is null
    or product_url ~ '^https?://[^[:space:]]+$'
    or product_url ~ '^/[^/[:space:]][^[:space:]]*$'
  );

create table if not exists public.contact_submissions (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 100),
  email text not null check (char_length(email) between 3 and 254),
  subject text not null check (char_length(subject) between 2 and 160),
  message text not null check (char_length(message) between 10 and 5000),
  status text not null default 'new' check (status in ('new', 'in_progress', 'resolved', 'spam')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.contact_submissions enable row level security;

create table if not exists public.api_rate_limits (
  bucket_key text primary key,
  request_count integer not null,
  window_started_at timestamptz not null,
  expires_at timestamptz not null
);
alter table public.api_rate_limits enable row level security;

create or replace function public.consume_api_rate_limit(
  p_bucket_key text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
  v_now timestamptz := clock_timestamp();
begin
  if p_limit < 1 or p_window_seconds < 1 or char_length(p_bucket_key) > 200 then
    raise exception 'Invalid rate-limit arguments.';
  end if;
  insert into public.api_rate_limits(bucket_key, request_count, window_started_at, expires_at)
  values (p_bucket_key, 1, v_now, v_now + make_interval(secs => p_window_seconds))
  on conflict (bucket_key) do update set
    request_count = case when api_rate_limits.expires_at <= v_now then 1 else api_rate_limits.request_count + 1 end,
    window_started_at = case when api_rate_limits.expires_at <= v_now then v_now else api_rate_limits.window_started_at end,
    expires_at = case when api_rate_limits.expires_at <= v_now then v_now + make_interval(secs => p_window_seconds) else api_rate_limits.expires_at end
  returning request_count into v_count;
  return v_count <= p_limit;
end;
$$;
revoke all on function public.consume_api_rate_limit(text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_api_rate_limit(text, integer, integer) to service_role;

drop policy if exists contact_submissions_admin_read on public.contact_submissions;
create policy contact_submissions_admin_read
on public.contact_submissions for select to authenticated
using (public.is_admin());

drop policy if exists contact_submissions_admin_update on public.contact_submissions;
create policy contact_submissions_admin_update
on public.contact_submissions for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop trigger if exists contact_submissions_set_updated_at on public.contact_submissions;
create trigger contact_submissions_set_updated_at
before update on public.contact_submissions
for each row execute function public.set_updated_at();

-- These functions are application-internal. Payment verification and admin
-- status changes must only pass through the service-role backed server DAL.
revoke all on function public.mark_commerce_razorpay_paid(uuid, text, text, jsonb) from public, anon, authenticated;
grant execute on function public.mark_commerce_razorpay_paid(uuid, text, text, jsonb) to service_role;

revoke all on function public.update_commerce_order_status(uuid, public.commerce_order_status, uuid, text, text) from public, anon, authenticated;
grant execute on function public.update_commerce_order_status(uuid, public.commerce_order_status, uuid, text, text) to service_role;

-- Direct customer cancellation derives ownership from auth.uid(). Service-role
-- callers may operate for admin workflows; clients cannot spoof actor identity.
revoke all on function public.cancel_commerce_order(uuid, uuid, uuid, text, text) from public, anon, authenticated;
grant execute on function public.cancel_commerce_order(uuid, uuid, uuid, text, text) to service_role;

create or replace function public.cancel_own_commerce_order(
  p_order_id uuid,
  p_reason text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required.' using errcode = '42501';
  end if;

  if not exists (
    select 1 from public.commerce_orders
    where id = p_order_id and customer_id = auth.uid()
  ) then
    raise exception 'Order not found.' using errcode = '42501';
  end if;

  perform public.cancel_commerce_order(
    p_order_id,
    auth.uid(),
    auth.uid(),
    'customer',
    p_reason
  );
end;
$$;

revoke all on function public.cancel_own_commerce_order(uuid, text) from public, anon;
grant execute on function public.cancel_own_commerce_order(uuid, text) to authenticated;

commit;
